package latpc

import (
	"sync"

	"github.com/sarchlab/akita/v5/hooking"
	"github.com/sarchlab/akita/v5/tracing"
)

// GroupMember identifies one coalesced memory transaction generated by a
// wavefront instruction. Position and Count preserve the instruction-local
// order and boundary; LaneMask preserves the originating wave64 lanes.
type GroupMember struct {
	InstructionID uint64
	RequestID     uint64
	Position      uint16
	Count         uint16
	VAddr         uint64
	LaneMask      uint64
}

// Last reports whether this is the final transaction from the instruction.
func (m GroupMember) Last() bool {
	return m.Count > 0 && m.Position+1 == m.Count
}

// MetadataRegistry follows group metadata as components replace one request
// with a child request. It is a simulator sidecar: protocol payloads, cache
// addresses, and baseline component timing are unchanged.
type MetadataRegistry struct {
	mu      sync.RWMutex
	members map[uint64]GroupMember
}

// NewMetadataRegistry creates an empty request-metadata registry.
func NewMetadataRegistry() *MetadataRegistry {
	return &MetadataRegistry{members: make(map[uint64]GroupMember)}
}

// Put associates metadata with a request ID.
func (r *MetadataRegistry) Put(requestID uint64, member GroupMember) {
	r.mu.Lock()
	r.members[requestID] = member
	r.mu.Unlock()
}

// Get returns metadata without changing its lifetime.
func (r *MetadataRegistry) Get(requestID uint64) (GroupMember, bool) {
	r.mu.RLock()
	member, ok := r.members[requestID]
	r.mu.RUnlock()
	return member, ok
}

// Move transfers metadata from a parent request/task to its child.
func (r *MetadataRegistry) Move(parentID, childID uint64) bool {
	r.mu.Lock()
	defer r.mu.Unlock()

	member, ok := r.members[parentID]
	if !ok {
		return false
	}
	delete(r.members, parentID)
	member.RequestID = childID
	r.members[childID] = member
	return true
}

// Delete releases request metadata.
func (r *MetadataRegistry) Delete(requestID uint64) {
	r.mu.Lock()
	delete(r.members, requestID)
	r.mu.Unlock()
}

// Len returns the number of live sidecar records.
func (r *MetadataRegistry) Len() int {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return len(r.members)
}

var runtimeMetadata = NewMetadataRegistry()

// ResetRuntimeMetadata clears metadata before building a new platform.
func ResetRuntimeMetadata() {
	runtimeMetadata = NewMetadataRegistry()
}

// RegisterRequestMetadata starts tracking a coalesced memory request.
func RegisterRequestMetadata(requestID uint64, member GroupMember) {
	runtimeMetadata.Put(requestID, member)
}

// RequestMetadata returns the group metadata that reached requestID.
func RequestMetadata(requestID uint64) (GroupMember, bool) {
	return runtimeMetadata.Get(requestID)
}

// ReleaseRequestMetadata ends tracking at a terminal translation component.
func ReleaseRequestMetadata(requestID uint64) {
	runtimeMetadata.Delete(requestID)
}

type metadataBridge struct {
	registry *MetadataRegistry
}

// Func follows the req_in/req_out parent chain emitted by Akita components.
// Moving rather than copying bounds the sidecar to in-flight requests.
func (h *metadataBridge) Func(ctx hooking.HookCtx) {
	if ctx.Pos == tracing.HookPosTaskEnd {
		task, ok := ctx.Item.(tracing.TaskEnd)
		if ok {
			h.registry.Delete(task.ID)
		}
		return
	}
	if ctx.Pos != tracing.HookPosTaskStart {
		return
	}
	task, ok := ctx.Item.(tracing.TaskStart)
	if !ok {
		return
	}
	switch task.Kind {
	case tracing.ReqInTaskKind, tracing.ReqOutTaskKind:
		h.registry.Move(task.ParentID, task.ID)
	}
}

// AttachMetadataBridge makes one request-transforming component preserve group
// metadata. The hook executes only host-side bookkeeping and adds no simulated
// pipeline stage or detector latency.
func AttachMetadataBridge(component tracing.NamedHookable) {
	component.AcceptHook(&metadataBridge{registry: runtimeMetadata})
}
